version: '3'
services:
  googlesync:
    build: .
    container_name: contacts_googlesync
    ports: 
      - "8011:8080"
    environment:
      - AUTHKEY
      - CONTACTSKEY
      - SYNCGROUP
      - AUTHURL
      - CONTACTSURL
    image: lucas42/lucos_contacts_googlesync
    extra_hosts:
      - "contacts.l42.eu:10.0.0.8"
      - "auth.l42.eu:10.0.0.8"