version: '3'
services:
  googlesync:
    build: .
    container_name: contacts_googlesync
    ports: 
      - "8011:8080"
    environment:
      - AUTHKEY
      - CONTACTSKEY
      - SYNCGROUP
      - AUTHURL
      - CONTACTSURL
    image: lucas42/lucos_contacts_googlesync